### ISSUE TITLE
Line spacing doesn't work with OpenDoors theme

### ISSUE THREAD

**Issue by gtirloni** [fluid-project/uio-wordpress-plugin#12]
## Describe the bug

The line spacing option does not seem to work with the theme used in the [OpenDoors](https://opendoors.idrc.ocadu.ca) website.

### To reproduce
1. Go to https://opendoors.idrc.ocadu.ca
2. Click on 'show display preferences'
3. Select different line spacing
4. Notice how the line spacing in the text is not modified

### Desktop
 - OS: Fedora Linux
 - Browser: Chrome
 - Version: 86

## Additional context or notes
Same behavior happens on Firefox 84

**Comment by jobara** [comment]
Unfortunately UIO isn't able override line-height set within the content. (See: [FLUID-4491](https://issues.fluidproject.org/browse/FLUID-4491)). In the case of the [OpenDoors](https://opendoors.idrc.ocadu.ca/) website, it appears that Foundation is used as a css framework and applying `line-height: 1.6` to at least all of the `<p>` elements.

**Comment by jobara** [comment]
The project is no longer actively maintained and will be archived.
