### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by kinti** [fluid-project/uio-wordpress-plugin#13]
how to open the main panel by default?

Sorry, but i can't do it...,

**Comment by jobara** [comment]
@kinti unfortunately there doesn't appear to be an easy way to accomplish this. At the moment we don't expose many options through the admin interface. We have hoped to improve this, but I don't have an ETA on when that might happen, nor what it might include. Additionally, this is not well supported in the underlying code either. I've filed a ticket, [FLUID-6628](https://issues.fluidproject.org/browse/FLUID-6628), regarding this.

**Comment by jobara** [comment]
The project is no longer actively maintained and will be archived.
