### ISSUE TITLE
settings panel opens under WordPress Twenty Fifteen sidebar

### ISSUE THREAD

**Issue by jimt** [fluid-project/uio-wordpress-plugin#3]
When using the **Twenty Fifteen** theme with WordPress 4.1.1, the settings panel opens _under_ the WordPress sidebar.

![settings-under-sidebar](https://cloud.githubusercontent.com/assets/180326/6861251/810eb6d8-d476-11e4-89e7-c7620bbd50f3.png)

**Comment by jobara** [comment]
The project is no longer actively maintained and will be archived.
