### ISSUE TITLE
Wrong URL for Plugin URI

### ISSUE THREAD

**Issue by cogdog** [fluid-project/uio-wordpress-plugin#6]
In `ui-options.php` the URL for Plugin URI is listed

`http://github.org/fluid-project/uio-wordpress-plugin`

but should be 

`http://github.com/fluid-project/uio-wordpress-plugin`

Was just checking repo from link in Plugins on my site.  Have been trying out the [WP Pusher](https://wppusher.com/) plugin for autoupdating from Github repos.

**Comment by jobara** [comment]
@cogdog thanks for the issue report, I've submitted a PR to address it.

**Comment by jhung** [comment]
Merged.
